"""Property-based equivalence tests for the HDF5 parser's fill-value handling.

Each test writes an HDF5 file via h5py, opens it both via xarray+h5netcdf and
via xarray+virtualizarr (manifest_store_from_hdf_url), and asserts the two
loaded datasets are identical at two layers:

  1. raw attribute layer (decode_cf=False) — exposes metadata bugs that CF
     decoding would otherwise mask (e.g. dropped attributes, wrong fill-value
     encoding, lost _Unsigned).
  2. decoded data layer (decode_cf=True) — the user-facing correctness
     check (mask_and_scale, _FillValue masking, scale_factor/add_offset,
     _Unsigned reinterpretation).

See docs/custom_parsers.md ("Fill values" and "Packing and scaling" sections)
for the rules these tests exercise.

The strategies in TestBasicEquivalence / TestPackedEquivalence /
TestUnsignedEquivalence generate the *full* parameter range that
`docs/custom_parsers.md` says the parser should support. Assertions are
plain `_assert_h5netcdf_virtualizarr_identical` (raw-attribute +
decoded-data) — no `xfail`, no `pytest.raises` adapter for cases that
don't work today.

This is intentional: the suite functions as an executable specification.
Failures are TODO items. Suite green = HDFParser stack matches spec.

Compound/structured dtypes can't be generated by the uniform-dtype
basic strategy and are covered by curated cases in `TestCompoundDtype`.

Shared infrastructure (sentinel, hypothesis profile registration,
equivalence assertion helpers, generic numeric-dtype strategy) lives in
`virtualizarr/tests/test_parsers/_fill_value_common.py` so other
parsers can reuse it without copy-paste.

CI throttling:
- VIRTUALIZARR_HYPOTHESIS_PROFILE=ci      -> max_examples=10  (faster)
- VIRTUALIZARR_HYPOTHESIS_PROFILE=thorough -> max_examples=50  (default)
- pytest -m "not hypothesis_tests"        -> skip this module entirely
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import pytest
import xarray as xr
from hypothesis import HealthCheck, example, given, settings
from hypothesis import strategies as st
from hypothesis.extra import numpy as npst

from virtualizarr.tests import requires_hdf5plugin, requires_imagecodecs
from virtualizarr.tests.test_parsers._fill_value_common import (
    _UNSET,
    assert_equivalent,
    base_numeric_dtype_strategy,
    base_pytestmark,
    register_hypothesis_profiles,
)
from virtualizarr.tests.test_parsers._fill_value_common import (
    data_in_dtype_strategy as _base_data_in_dtype_strategy,
)
from virtualizarr.tests.test_parsers._fill_value_common import (
    value_in_dtype_strategy as _base_value_in_dtype_strategy,
)
from virtualizarr.tests.utils import manifest_store_from_hdf_url

pytestmark = base_pytestmark()
register_hypothesis_profiles()


@dataclass
class _DatasetSpec:
    """A self-contained description of one HDF5 file to write for testing.

    Every field passed to _write_hdf5 by tests should land in this dataclass
    so failures shrink to a single repr-able value.
    """

    dtype: np.dtype
    data: np.ndarray
    dataset_fillvalue: Any = _UNSET
    fill_value_attr: Any = _UNSET
    scale_factor: float | None = None
    add_offset: float | None = None
    unsigned: bool = False
    chunks: tuple[int, ...] | None = None
    # Free-form attributes written verbatim to the dataset. Used to cover
    # CF attributes that xarray passes through without special processing
    # (missing_value, valid_range, valid_min, valid_max). The raw-attrs
    # invariant catches any drop automatically.
    extra_attrs: dict[str, Any] | None = None


def _write_hdf5(
    filepath: Path | str,
    *,
    dtype: np.dtype,
    data: np.ndarray,
    dataset_fillvalue: Any = _UNSET,
    fill_value_attr: Any = _UNSET,
    scale_factor: float | None = None,
    add_offset: float | None = None,
    unsigned: bool = False,
    chunks: tuple[int, ...] | None = None,
    extra_attrs: dict[str, Any] | None = None,
) -> str:
    """Write a single-variable HDF5 file with the requested fill-value shape.

    Returns the file:// URL for use with manifest_store_from_hdf_url.
    """
    filepath = str(filepath)

    create_kwargs: dict[str, Any] = {"name": "data", "data": data, "dtype": dtype}
    if chunks is not None:
        create_kwargs["chunks"] = chunks
    if dataset_fillvalue is not _UNSET:
        create_kwargs["fillvalue"] = dataset_fillvalue

    with h5py.File(filepath, "w") as f:
        dset = f.create_dataset(**create_kwargs)
        if fill_value_attr is not _UNSET:
            dset.attrs["_FillValue"] = fill_value_attr
        if scale_factor is not None:
            dset.attrs["scale_factor"] = scale_factor
        if add_offset is not None:
            dset.attrs["add_offset"] = add_offset
        if unsigned:
            dset.attrs["_Unsigned"] = "true"
        if extra_attrs is not None:
            for k, v in extra_attrs.items():
                dset.attrs[k] = v
        # Attach a real dim scale to each axis so xarray+h5netcdf and the
        # HDF parser both produce named "dim_<i>" dims instead of
        # phony_dim_0 — keeps equivalence assertions about fill values,
        # not dim naming.
        for axis, size in enumerate(data.shape):
            scale_name = f"dim_{axis}"
            dim = f.create_dataset(scale_name, data=np.arange(size))
            dim.make_scale(scale_name)
            dset.dims[axis].attach_scale(dim)

    return f"file://{filepath}"


def _open_virtualizarr(filepath: str, *, decode_cf: bool) -> xr.Dataset:
    """Open `filepath` via virtualizarr's HDFParser (manifest store) + xarray's
    zarr backend. Plugged into the shared equivalence helpers as the
    `open_observed` callback.
    """
    manifest_store = manifest_store_from_hdf_url(f"file://{filepath}")
    return xr.open_dataset(
        manifest_store,
        engine="zarr",
        consolidated=False,
        zarr_format=3,
        decode_cf=decode_cf,
    )


def _open_h5netcdf(filepath: str, *, decode_cf: bool) -> xr.Dataset:
    """Open `filepath` via xarray+h5netcdf. The reference engine for the HDF
    equivalence sweep — what a user expects to see when reading the file
    directly without virtualizarr.
    """
    return xr.open_dataset(filepath, engine="h5netcdf", decode_cf=decode_cf)


def _assert_h5netcdf_virtualizarr_identical(filepath: str) -> None:
    """Run both raw-attribute and decoded-data invariants against the HDF
    parser. Thin wrapper around the shared helper that binds the engines.
    """
    assert_equivalent(
        filepath,
        open_observed=_open_virtualizarr,
        open_reference=_open_h5netcdf,
    )


def test_module_loads():
    """Smoke test: confirms the module imports, the marker registers,
    and hypothesis profiles loaded without error.
    """
    assert settings().max_examples in (10, 50)


def test_write_hdf5_basic_roundtrip(tmp_path):
    """_write_hdf5 writes data, dataset.fillvalue, _FillValue attr,
    and dim scale that h5py can read back."""
    url = _write_hdf5(
        tmp_path / "data.nc",
        dtype=np.dtype("f8"),
        data=np.array([1.0, 2.0, 3.0], dtype="f8"),
        dataset_fillvalue=-9999.0,
        fill_value_attr=-9999.0,
        chunks=(2,),
    )
    assert url.startswith("file://")

    with h5py.File(url.removeprefix("file://"), "r") as f:
        dset = f["data"]
        np.testing.assert_array_equal(dset[:], [1.0, 2.0, 3.0])
        assert dset.fillvalue == -9999.0
        assert dset.attrs["_FillValue"] == -9999.0
        assert dset.chunks == (2,)
        assert len(dset.dims[0]) == 1
        assert dset.dims[0][0].name.lstrip("/") == "dim_0"


def test_write_hdf5_unset_skips_fillvalue(tmp_path):
    """When dataset_fillvalue=_UNSET, h5py uses its dtype default;
    when fill_value_attr=_UNSET, no _FillValue attribute is written.
    """
    url = _write_hdf5(
        tmp_path / "data.nc",
        dtype=np.dtype("i4"),
        data=np.array([1, 2, 3], dtype="i4"),
        # both fill axes left UNSET
    )
    with h5py.File(url.removeprefix("file://"), "r") as f:
        assert "_FillValue" not in f["data"].attrs


def test_equivalence_helper_passes_on_simple_file(tmp_path):
    """A trivial float64 file with no fill values must round-trip
    identically through both paths."""
    url = _write_hdf5(
        tmp_path / "simple.nc",
        dtype=np.dtype("f8"),
        data=np.array([1.0, 2.0, 3.0, 4.0], dtype="f8"),
    )
    _assert_h5netcdf_virtualizarr_identical(url.removeprefix("file://"))


def _h5py_compatible_dtype_strategy() -> st.SearchStrategy[np.dtype]:
    """Sample one of the dtypes h5py can store in a dataset.

    Extends `base_numeric_dtype_strategy()` (bool/int*/uint*/float*/complex*)
    with HDF5-specific kinds: fixed-bytes `S*` and vlen utf-8
    (`h5py.string_dtype()`, kind `O`). Both currently expose downstream
    breakages — that's intentional: the suite *highlights* breakages
    rather than hides them.

    Structured/compound dtypes are excluded — they can't be parametrised
    by a single `np.dtype` and are covered by curated cases in
    `TestCompoundDtype`.
    """
    return st.one_of(
        base_numeric_dtype_strategy(),
        st.sampled_from(
            [
                np.dtype("S1"),
                np.dtype("S5"),
                np.dtype("S20"),
                h5py.string_dtype(),  # vlen utf-8 (kind 'O' under the hood)
            ]
        ),
    )


def _value_in_dtype_strategy(dtype: np.dtype) -> st.SearchStrategy[Any]:
    """Return a strategy producing a value compatible with `dtype`.

    Delegates to `base_value_in_dtype_strategy` for the universally-supported
    kinds and adds the HDF-specific vlen-string branch (kind `O`).
    """
    if dtype.kind == "O":  # h5py.string_dtype() — vlen utf-8
        return st.text(min_size=0, max_size=20)
    return _base_value_in_dtype_strategy(dtype)


def _data_in_dtype_strategy(
    dtype: np.dtype, shape: tuple[int, ...]
) -> st.SearchStrategy[np.ndarray]:
    """Generate a numpy array of the given dtype and shape.

    Branches on dtype because `hypothesis.extra.numpy.arrays` doesn't
    handle h5py's vlen-string dtype well — we have to build a flat list
    and reshape.
    """
    if dtype.kind == "O":
        n = int(np.prod(shape)) if len(shape) else 1
        return st.lists(
            st.text(min_size=0, max_size=20),
            min_size=n,
            max_size=n,
        ).map(lambda xs: np.array(xs, dtype=h5py.string_dtype()).reshape(shape))
    return _base_data_in_dtype_strategy(dtype, shape)


@st.composite
def _basic_dataset_strategy(draw) -> _DatasetSpec:
    dtype = draw(_h5py_compatible_dtype_strategy())
    # 1- to 3-D shapes with modest sides; covers axis-naming, multi-chunk,
    # and chunk-vs-shape edge cases without blowing up data volume.
    shape = draw(npst.array_shapes(min_dims=1, max_dims=3, min_side=1, max_side=8))
    chunks_choice = draw(st.booleans())
    chunks = (
        tuple(draw(st.integers(min_value=1, max_value=size)) for size in shape)
        if chunks_choice
        else None
    )
    data = draw(_data_in_dtype_strategy(dtype, shape))
    fill_in_dtype = draw(_value_in_dtype_strategy(dtype))
    dataset_fillvalue = draw(st.sampled_from([_UNSET, fill_in_dtype]))
    fill_value_attr = draw(st.sampled_from([_UNSET, fill_in_dtype]))
    return _DatasetSpec(
        dtype=dtype,
        data=data,
        dataset_fillvalue=dataset_fillvalue,
        fill_value_attr=fill_value_attr,
        chunks=chunks,
    )


def _spec_to_url(spec: _DatasetSpec, tmp_path: Path) -> str:
    """Translate a _DatasetSpec into a written file and return its path
    (without file:// prefix, for use with the equivalence helper)."""
    url = _write_hdf5(
        tmp_path / "data.nc",
        dtype=spec.dtype,
        data=spec.data,
        dataset_fillvalue=spec.dataset_fillvalue,
        fill_value_attr=spec.fill_value_attr,
        scale_factor=spec.scale_factor,
        add_offset=spec.add_offset,
        unsigned=spec.unsigned,
        chunks=spec.chunks,
        extra_attrs=spec.extra_attrs,
    )
    return url.removeprefix("file://")


# Curated examples — each forces a specific dtype/fill combination we want
# guaranteed coverage of, separate from the random strategy draws.
_BASIC_EXAMPLES = [
    # NaN float _FillValue
    _DatasetSpec(
        dtype=np.dtype("f8"),
        data=np.array([1.0, 2.0, 3.0], dtype="f8"),
        fill_value_attr=np.nan,
    ),
    # uint8 with both dataset.fillvalue and matching _FillValue
    _DatasetSpec(
        dtype=np.dtype("u1"),
        data=np.array([1, 2, 3], dtype="u1"),
        dataset_fillvalue=255,
        fill_value_attr=255,
    ),
    # bool _FillValue=True
    _DatasetSpec(
        dtype=np.dtype("?"),
        data=np.array([True, False, True], dtype="?"),
        fill_value_attr=True,
    ),
    # vlen utf-8 with empty-string sentinel _FillValue
    _DatasetSpec(
        dtype=h5py.string_dtype(),
        data=np.array(["a", "b"], dtype=h5py.string_dtype()),
        fill_value_attr="",
    ),
    # vlen utf-8 with a real sentinel value
    _DatasetSpec(
        dtype=h5py.string_dtype(),
        data=np.array(["a", "b"], dtype=h5py.string_dtype()),
        fill_value_attr="MISSING",
    ),
    # vlen utf-8 with no _FillValue at all
    _DatasetSpec(
        dtype=h5py.string_dtype(),
        data=np.array(["a", "b"], dtype=h5py.string_dtype()),
    ),
    # S10 with empty-bytes sentinel _FillValue
    _DatasetSpec(
        dtype=np.dtype("S10"),
        data=np.array([b"hello", b"world"], dtype="S10"),
        fill_value_attr=b"",
    ),
    # S5 with a real sentinel _FillValue
    _DatasetSpec(
        dtype=np.dtype("S5"),
        data=np.array([b"a", b"b"], dtype="S5"),
        fill_value_attr=b"x",
    ),
]


_BASIC_EXAMPLE_IDS = [
    "float64-nan-fill",
    "uint8-with-fill",
    "bool-fill",
    "vlen-empty-fill",
    "vlen-sentinel-fill",
    "vlen-no-fill",
    "S10-empty-fill",
    "S5-sentinel-fill",
]


@requires_hdf5plugin
@requires_imagecodecs
class TestBasicEquivalence:
    """Equivalence sweep across the dtype × fill matrix.

    The random-draw strategy generates the *full* parameter range that
    `docs/custom_parsers.md` says the parser should support — including
    string-kind dtypes with explicit `_FillValue`, vlen-utf-8 with and
    without fill, etc.

    Curated examples and random draws are **separate test methods** so
    pytest-xdist can parallelise the curated cases and a single failing
    example doesn't shadow the others. Each curated example shows as
    its own test ID (`test_equivalence_curated[<name>]`); random draws
    aggregate under `test_equivalence_random`.

    The assertion is plain `_assert_h5netcdf_virtualizarr_identical`.
    Cases the parser/stack doesn't handle correctly today **will fail**;
    those failures are the to-fix list. Suite green = fixes complete.
    """

    @pytest.mark.parametrize("spec", _BASIC_EXAMPLES, ids=_BASIC_EXAMPLE_IDS)
    def test_equivalence_curated(self, spec, tmp_path):
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)

    # tmp_path is function-scoped, but each hypothesis example writes the
    # same `data.nc` and reads it before the next example runs. The
    # overwrite-in-place is intentional.
    @settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
    @given(spec=_basic_dataset_strategy())
    def test_equivalence_random(self, spec, tmp_path):
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)


# String-dtype known failures are now covered by _BASIC_EXAMPLES (curated
# entries) + random draws (via _h5py_compatible_dtype_strategy) inside
# TestBasicEquivalence. The `_expected_failure_for(spec)` predicate
# asserts the precise failure mode, so a change there is detected.
# No separate test class needed.


@st.composite
def _packed_dataset_strategy(draw) -> _DatasetSpec:
    """Packed-data scenarios: integer storage + scale_factor + add_offset
    + _FillValue in the packed (encoded) domain.

    Per docs/custom_parsers.md "Fill values in packed data": the
    _FillValue must be in the packed domain; xarray applies CFMaskCoder
    before CFScaleOffsetCoder on decode.
    """
    dtype = draw(
        st.sampled_from(
            [
                np.dtype("i2"),
                np.dtype("i4"),
                np.dtype("u2"),
                np.dtype("u4"),
            ]
        )
    )
    scale_factor = draw(
        st.floats(min_value=1e-3, max_value=1e3, allow_nan=False, allow_infinity=False)
    )
    add_offset = draw(
        st.floats(min_value=-1e3, max_value=1e3, allow_nan=False, allow_infinity=False)
    )
    shape = draw(npst.array_shapes(min_dims=1, max_dims=3, min_side=1, max_side=8))
    data = draw(npst.arrays(dtype=dtype, shape=shape))
    fill_value_attr = draw(_value_in_dtype_strategy(dtype))
    return _DatasetSpec(
        dtype=dtype,
        data=data,
        fill_value_attr=fill_value_attr,
        scale_factor=scale_factor,
        add_offset=add_offset,
    )


_PACKED_EXAMPLES = [
    # int16 packed: scale=0.01, offset=0, _FillValue=-9999 (canonical CF case)
    _DatasetSpec(
        dtype=np.dtype("i2"),
        data=np.array([100, 200, 300], dtype="i2"),
        fill_value_attr=np.int16(-9999),
        scale_factor=0.01,
        add_offset=0.0,
    ),
    # uint16 packed: scale=0.1, offset=1000, _FillValue=0
    _DatasetSpec(
        dtype=np.dtype("u2"),
        data=np.array([10, 20, 30], dtype="u2"),
        fill_value_attr=np.uint16(0),
        scale_factor=0.1,
        add_offset=1000.0,
    ),
]


@requires_hdf5plugin
@requires_imagecodecs
class TestPackedEquivalence:
    @settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
    @given(spec=_packed_dataset_strategy())
    @example(spec=_PACKED_EXAMPLES[0])
    @example(spec=_PACKED_EXAMPLES[1])
    def test_equivalence(self, spec, tmp_path):
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)


@st.composite
def _unsigned_dataset_strategy(draw) -> _DatasetSpec:
    """Signed-integer storage with _Unsigned="true" attribute.

    Per docs/custom_parsers.md "_Unsigned": fill value is interpreted in
    the unsigned domain; e.g. _FillValue=-1 stored as int16 corresponds
    to 65535 when reinterpreted as uint16.
    """
    dtype = draw(
        st.sampled_from(
            [
                np.dtype("i1"),
                np.dtype("i2"),
                np.dtype("i4"),
                np.dtype("i8"),
            ]
        )
    )
    shape = draw(npst.array_shapes(min_dims=1, max_dims=3, min_side=1, max_side=8))
    data = draw(npst.arrays(dtype=dtype, shape=shape))
    fill_value_attr = draw(_value_in_dtype_strategy(dtype))
    return _DatasetSpec(
        dtype=dtype,
        data=data,
        fill_value_attr=fill_value_attr,
        unsigned=True,
    )


_UNSIGNED_EXAMPLES = [
    # int16 stored, reinterpreted as uint16; _FillValue=-1 -> 65535
    _DatasetSpec(
        dtype=np.dtype("i2"),
        data=np.array([1, 2, 3], dtype="i2"),
        fill_value_attr=np.int16(-1),
        unsigned=True,
    ),
]


@requires_hdf5plugin
@requires_imagecodecs
class TestUnsignedEquivalence:
    @settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
    @given(spec=_unsigned_dataset_strategy())
    @example(spec=_UNSIGNED_EXAMPLES[0])
    def test_equivalence(self, spec, tmp_path):
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)


# Compound/structured dtypes don't fit the orthogonal axes of the basic /
# packed / _Unsigned strategies (no integer/float kind, no scale_factor
# semantics, no signed-vs-unsigned reinterpretation). They're also too
# combinatorially varied to draw from a hypothesis strategy without heavy
# `assume()` filtering. A handful of curated examples is enough.
_COMPOUND_DTYPES_AND_FILLS = [
    (
        np.dtype([("a", "i4"), ("b", "f8")]),
        np.array([(1, 1.0), (2, 2.0), (3, 3.0)], dtype=[("a", "i4"), ("b", "f8")]),
        np.array((0, 0.0), dtype=[("a", "i4"), ("b", "f8")]),
    ),
    (
        np.dtype([("x", "u2"), ("y", "u2"), ("z", "u2")]),
        np.array(
            [(10, 20, 30), (40, 50, 60)],
            dtype=[("x", "u2"), ("y", "u2"), ("z", "u2")],
        ),
        np.array(
            (65535, 65535, 65535),
            dtype=[("x", "u2"), ("y", "u2"), ("z", "u2")],
        ),
    ),
]


@requires_hdf5plugin
@requires_imagecodecs
class TestCompoundDtype:
    """Compound/structured-dtype datasets with _FillValue.

    Compound dtypes can't be generated by the uniform-dtype basic
    strategy (no single `np.dtype` to sample); they're covered here as
    curated parametrized cases. Assertion is plain equivalence — any
    failure is a real issue to fix.
    """

    @pytest.mark.parametrize(
        "dtype,data,fill_value_attr",
        _COMPOUND_DTYPES_AND_FILLS,
        ids=["two-field", "three-field"],
    )
    def test_equivalence(self, dtype, data, fill_value_attr, tmp_path):
        spec = _DatasetSpec(dtype=dtype, data=data, fill_value_attr=fill_value_attr)
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)


# Cross-axis interactions: the basic / packed / _Unsigned classes are
# deliberately orthogonal so each hypothesis strategy stays clean, but
# real files combine multiple features. These curated examples cover the
# combinations most likely to harbor latent bugs: packed + chunked + fill,
# _Unsigned + chunked + fill, multi-dim + packed + fill, multi-dim + _Unsigned.
_COMBINED_EXAMPLES = [
    # packed + chunked
    _DatasetSpec(
        dtype=np.dtype("i2"),
        data=np.arange(100, dtype="i2"),
        fill_value_attr=np.int16(-9999),
        scale_factor=0.01,
        add_offset=0.0,
        chunks=(10,),
    ),
    # _Unsigned + chunked + explicit dataset.fillvalue
    _DatasetSpec(
        dtype=np.dtype("i2"),
        data=np.arange(64, dtype="i2"),
        dataset_fillvalue=np.int16(-1),
        fill_value_attr=np.int16(-1),
        unsigned=True,
        chunks=(8,),
    ),
    # 2D packed + chunked
    _DatasetSpec(
        dtype=np.dtype("i4"),
        data=np.arange(24, dtype="i4").reshape(4, 6),
        fill_value_attr=np.int32(-32768),
        scale_factor=0.001,
        add_offset=-100.0,
        chunks=(2, 3),
    ),
    # 3D _Unsigned
    _DatasetSpec(
        dtype=np.dtype("i1"),
        data=np.arange(8, dtype="i1").reshape(2, 2, 2),
        fill_value_attr=np.int8(-1),
        unsigned=True,
    ),
    # packed + dataset.fillvalue in packed domain matching _FillValue
    _DatasetSpec(
        dtype=np.dtype("u2"),
        data=np.array([10, 20, 30], dtype="u2"),
        dataset_fillvalue=np.uint16(65535),
        fill_value_attr=np.uint16(65535),
        scale_factor=0.1,
        add_offset=0.0,
    ),
]


@requires_hdf5plugin
@requires_imagecodecs
class TestCombinedEquivalence:
    @pytest.mark.parametrize(
        "spec",
        _COMBINED_EXAMPLES,
        ids=[
            "packed+chunked",
            "unsigned+chunked+fill",
            "2D+packed+chunked",
            "3D+unsigned",
            "packed+matching-fill",
        ],
    )
    def test_equivalence(self, spec, tmp_path):
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)


# Extra-CF-attribute scenarios: xarray does not specially process these
# attributes; the parser MUST round-trip them as-is. The raw-attrs
# invariant (decode_cf=False) is what surfaces a drop or transformation
# directly; the decoded-data invariant covers the user-facing path.
_EXTRA_ATTR_EXAMPLES = [
    # missing_value alongside _FillValue
    _DatasetSpec(
        dtype=np.dtype("f4"),
        data=np.array([1.0, 2.0, 3.0], dtype="f4"),
        fill_value_attr=np.float32(-9999.0),
        extra_attrs={"missing_value": np.float32(-9998.0)},
    ),
    # valid_range as a 2-element array
    _DatasetSpec(
        dtype=np.dtype("i2"),
        data=np.array([10, 20, 30], dtype="i2"),
        extra_attrs={"valid_range": np.array([0, 100], dtype="i2")},
    ),
    # valid_min / valid_max as separate scalars
    _DatasetSpec(
        dtype=np.dtype("f8"),
        data=np.array([0.5, 1.0, 1.5], dtype="f8"),
        extra_attrs={"valid_min": 0.0, "valid_max": 2.0},
    ),
    # missing_value + valid_range together
    _DatasetSpec(
        dtype=np.dtype("i4"),
        data=np.array([1, 2, 3], dtype="i4"),
        fill_value_attr=np.int32(-1),
        extra_attrs={
            "missing_value": np.int32(-2),
            "valid_range": np.array([0, 1000], dtype="i4"),
        },
    ),
]


@requires_hdf5plugin
@requires_imagecodecs
class TestExtraAttributes:
    """Pass-through of missing_value / valid_range / valid_min / valid_max.

    xarray does not specially process these CF attributes — the parser
    must preserve them verbatim. The raw-attrs assertion catches any drop
    or transformation directly.
    """

    @pytest.mark.parametrize(
        "spec",
        _EXTRA_ATTR_EXAMPLES,
        ids=[
            "missing_value+fill",
            "valid_range",
            "valid_min+valid_max",
            "missing_value+valid_range",
        ],
    )
    def test_equivalence(self, spec, tmp_path):
        filepath = _spec_to_url(spec, tmp_path)
        _assert_h5netcdf_virtualizarr_identical(filepath)
