name: readthedocs/actions
# on:
#   pull_request_target:
#     types:
#       - opened
#     # paths:
#     #   - "docs/**"


on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "ndpyramid"
