name: Minimum-versions

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, synchronize, labeled]
    paths-ignore:
    - 'docs/**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-upstream:
    name: minimum-versions-build
    if: |
      always()
      && (
          (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
          || contains( github.event.pull_request.labels.*.name, 'test-upstream')
      )
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.13
        with:
          pixi-version: v0.49.0
          environments: minimum-versions

      - name: List installed libraries
        run: |
          pixi list --environment minimum-versions
      - name: Determine test type
        id: test-type
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]] && \
             [[ "${{ contains(github.event.pull_request.labels.*.name, 'test-slow') }}" == "true" ]]; then
            echo "run-slow=true" >> $GITHUB_OUTPUT
            echo "Running slow tests due to 'test-slow' label"
          else
            echo "run-slow=false" >> $GITHUB_OUTPUT
            echo "Running standard tests (skipping slow tests)"
          fi

      - name: Run Tests
        run: |
          if [[ "${{ steps.test-type.outputs.run-slow }}" == "true" ]]; then
            pixi run -e minimum-versions run-tests-including-slow
          else
            pixi run -e minimum-versions run-tests-xml-cov
          fi
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
